### ISSUE TITLE
Some issues on  linux/gcc 10.3

### ISSUE THREAD

**Issue by philip-davis** [sci-visus/idx2#4]
1. Receiving an error:

```
 oid idx2::Print(idx2::printer*, const idx2::array<t>&)’:
/home/pdavis/idx2/Source/Core/Format.h:33:3: error: there are no arguments to ‘idx2_Print’ that depend on a template parameter, so a declaration of ‘idx2_Print’ must be available
```

Which can be reduced to a warning with '-fpermissive`. 

2.
```
 #if defined(__clang__)
```
Has a trailing tick (`) at a couple different places, which gcc doesn't like.

3. The following define in FileSystem.cpp (line 27) causes gcc some parsing confusion:
```
#define stat struct stat
```
in combination with the define on line 27, it causes line 220 to expand to a syntax error. I'm not sure what the portable solution is, but for linux I could just remove the line 27 define and change line 219 to struct stat S.

4. Pthread isn't being  linked for linux machines.

5. GCC scope struct stat from the idx2 namespace on line 10786 of idx2.hpp, and I can't figure out how to make it not do so. I finally resorted to renaming idx2::stat to idx2::idx_stat, which is somewhat ugly and requires changing about a dozen variable types  just after line 40609.

6. Source/Core/String.cpp has to explicitly include cerrno in gcc

**Comment by hoang-dt** [comment]
All of these issues should have been fixed. Please check out the latest commit.
